services:
  mongodb:
	image: mongo
	container_name: mongo_db
	ports:
		- 27017: 27017
		volumes:
		- mongo:/data
		environment:
		- MONGO_INITDB_ROOT_USERNAME=aliboy
		- MONGO_INITDB_ROOT_PASSWORD=aliboy
	mongo-express:
		image: mongo-express
		container_name: mongo_express
		restart: always
		ports:
			-8081: 8081
		environment:
			-ME_CONFIG_MONGODB_ADMINUSERNAME=aliboy
			-ME_CONFIG_MONGODB_ADMINPASSWORD=aliboy
			-ME_CONFIG_MONGODB_SERVER=mongodb
		volumes:
			mongo: 